### ISSUE TITLE
pre-rendered waveforms

### ISSUE THREAD

**Issue by t22james** [mspae/react-wavesurfer#14]
The documentation on original wavesurfer is a bit light, but it seems like to enable pre-rendered waveforms one would use a load like so
```
wavesurfer.load('../media/demo.wav', [
0.0218, 0.0183, 0.0165, 0.0198, 0.2137, 0.2888, 0.2313, 0.15, 0.2542, 0.2538, 0.2358, 0.1195, 0.1591, 0.2599, 0.2742, 0.1447, 0.2328, 0.1878, 0.1988, 0.1645, 0.1218, 0.2005, 0.2828, 0.2051, 0.1664, 0.1181, 0.1621, 0.2966, 0.189, 0.246, 0.2445, 0.1621, 0.1618, 0.189, 0.2354, 0.1561, 0.1638, 0.2799, 0.0923, 0.1659, 0.1675, 0.1268, 0.0984, 0.0997, 0.1248, 0.1495, 0.1431, 0.1236, 0.1755, 0.1183, 0.1349, 0.1018, 0.1109, 0.1833, 0.1813, 0.1422, 0.0961, 0.1191, 0.0791, 0.0631, 0.0315, 0.0157, 0.0166, 0.0108
        ]);
```
(taken from main.js http://wavesurfer-js.org/example/audio-element/main.js on the example here http://wavesurfer-js.org/example/audio-element/)

But it appears that react-wavesurfer doesn't allow this? From what I can gather it will only pass the audio file into the wavesurfer.load, without an option to also pass the waveform. Is there any chance you could add in that extra argument? or is this already possible and i'm missing something?

**Comment by mspae** [comment]
You're right this is currently not possible. But it is relatively trivial to implement. Will try and get round to doing it within the next week.

**Comment by mspae** [comment]
Sorry, accidentally closed.

**Comment by t22james** [comment]
Excellent! 
Hey @mspae anychase you could get this fix into your master? 
Really keen to get this through npm! :)

**Comment by mspae** [comment]
@t22james This has been merged now, so you can use peaks! (see [this example](https://github.com/mspae/react-wavesurfer/blob/master/example/components/peaks.js))
