### ISSUE TITLE
Equalizer

### ISSUE THREAD

**Issue by Fiorello** [mspae/react-wavesurfer#16]
Hi, I would like to use the waveform equalizer. How can I do?

thanks

**Comment by mspae** [comment]
The [equalizer example](https://github.com/katspaugh/wavesurfer.js/blob/master/example/equalizer/main.js) of wavesurfer hooks into the `ready` event callback. We can do pretty much the same by using the `onReady` callback prop. This callback also receives the wavesurfer instance as argument (see [docs](https://github.com/mspae/react-wavesurfer#onwavesurferevent-function)) – So you can the just use that to do the same stuff as the equalizer example.
