### ISSUE TITLE
regions plugin seems not working

### ISSUE THREAD

**Issue by vim-zz** [mspae/react-wavesurfer#20]
when building and running the example it does not show no region

**Comment by mspae** [comment]
Confirmed, I believe when using the build it works, but not when using the dev server. The reason for this is that the original `WaveSurfer` object does not get exposed by webpack in a way which allows the Region and Timeline plugins to attach themselves as new properties to it. I'm looking into this. Comments and ideas welcome!

Thanks for the issue!

**Comment by mspae** [comment]
I fixed this by exposing the `WaveSurfer` object by using the `expose-loader`. See https://github.com/mspae/react-wavesurfer/commit/ca9b8aef9e63147756daea3abc7f12afc7ad85ef
