### ISSUE TITLE
Resizing window causes wavesurfer to stop playback

### ISSUE THREAD

**Issue by Jahosh** [mspae/react-wavesurfer#24]
Hello, first and foremost thanks for the easy to use package. I have one issue though, as of right now when I resize the browser window during playback the wavesurfer always stops playing. Is this normal? If not, could you let me know how I could avoid this?

**Comment by mspae** [comment]
Hello @Jahosh – This most definitely is a bug. With me the playback does not stop when resizing, but the position is reset to 0 (the audio plays from the beginning) – Thanks for filing!

**Comment by mspae** [comment]
Version 0.8.2 should address this issue. The playback is being stopped while resizing and the playback state and position is restored afterwards. (ref https://github.com/mspae/react-wavesurfer/commit/ff54576984638e678837537d5518bdcd4f5ed674)
