### ISSUE TITLE
Resizing window causes audio pops/crackles

### ISSUE THREAD

**Issue by Jahosh** [mspae/react-wavesurfer#25]
Hello,

I've noticed that when I resize the browser window containing the react-wavesurfer component I hear clicks and crackles during audio playback. I'm guessing it might have to do with how the waveform is trying to redraw itself? Is there a work-around for this?

**Comment by mspae** [comment]
The playback is being stopped while resizing and the playback state and position is restored afterwards. This is because otherwise the position gets reset to 0 when you resize. I'm afraid this will have to do until resizing is better supported by `wavesurfer.js`.
