### ISSUE TITLE
Clarification around importing and using plugins

### ISSUE THREAD

**Issue by torbensko** [mspae/react-wavesurfer#27]
It would be useful if the readme could clarify how to import and use the plugins. Whilst the included examples cover the plugins, they're imported locally rather than through npm. I'm sure it's pretty simple to import, but so far everything I've tried hasn't worked.

**Comment by mspae** [comment]
Try with `var Regions = require('react-wavesurfer/lib/plugins/regions');`

**Comment by torbensko** [comment]
Thanks for the clarification.

It would be useful to mention this in the readme or provide an example that uses the npm package, i.e. not imported using a relative path. Just a suggestion.
