### ISSUE TITLE
playing true by default

### ISSUE THREAD

**Issue by omerts** [mspae/react-wavesurfer#31]
Hey,

When "playing" prop is true by default, player doesn't start playing until second render. 

During componentDidMount, there is not check for playing prop, and play() isn't called on underlying _wavesurfer instance. The result is that the player isn't playing until the next render, where componentWillReceiveProps is calling the play() function. 

Also, before play() (or pause()) is called wavesurfer's ready event is never raised. 

Omer

**Comment by TrevorHinesley** [comment]
@mspae this can be fixed by adding:

```
      // set initial playing state
      if (this.props.playing) {
        this.wavesurfer.play()
      }
```

to the ready callback.

**Comment by mspae** [comment]
@TrevorHinesley Awesome. can you open a PR?
