### ISSUE TITLE
Module not found: 'wavesurfer.js'

### ISSUE THREAD

**Issue by niblius** [mspae/react-wavesurfer#35]
Hi, everyone!
When I am trying to import react-wavesurfer, I am getting an error saying:

> 
> Error in ./~/react-wavesurfer/lib/react-wavesurfer.min.js
> Module not found: 'wavesurfer.js' in /home/username/Projects/test/frontend/node_modules/react-wavesurfer/lib
> 
>  @ ./~/react-wavesurfer/lib/react-wavesurfer.min.js 1:99-123

Although, the wavesurfer package (https://www.npmjs.com/package/wavesurfer) is installed.
First I tried to add the following to webpack config:
```
  {
    test: require.resolve("wavesurfer.js"),
    loader: "expose?WaveSurfer"
  }
```

and

```
  {
    test: require.resolve("wavesurfer.js"),
    loader: "expose-loader?WaveSurfer"
  }

```
but I received the similar error saying that there is no module wavesurfer.js. And indeed there was no module called "wavesurfer.js", but there was "wavesurfer" module. So I went to node_modules/react-wavesurfer/lib/react-wavesurfer.min.js and changed `require("wavesurfer.js")` to `require("wavesurfer") `and everything started working. Should I use another wavesurfer npm package or is this a bug?
Thank you.

**Comment by davidflores2** [comment]
Same error here...

**Comment by niblius** [comment]
Ok, I found solution. We should do install "wavesurfer.js" package instead of "wavesurfer".
So do: 
npm uninstall wavesurfer
npm install wavesurfer.js

Thanks everyone.

**Comment by reaganscofield** [comment]
i created react app with npm create-react-app where can find find webpack to add the following codes

 {
    test: require.resolve("wavesurfer.js"),
    loader: "expose?WaveSurfer"
  }
and

  {
    test: require.resolve("wavesurfer.js"),
    loader: "expose-loader?WaveSurfer"
  }

i get also the same error it can't find modules:

node_modules/react-wavesurfer/lib/react-wavesurfer.min.js
Module not found: Can't resolve 'wavesurfer.js' in 'C:\Users\reaganm\Desktop\wavesurfer\node_modules\react-wavesurfer\lib'
