### ISSUE TITLE
When passing a new audioFile prop, an error occurs

### ISSUE THREAD

**Issue by TrevorHinesley** [mspae/react-wavesurfer#36]
Here's the error:

`Uncaught DOMException: Failed to execute 'stop' on 'AudioScheduledSourceNode': cannot call stop without calling start first.`

Any ideas?

**Comment by TrevorHinesley** [comment]
Fixed. With the new additions of setting playback in the ready function, this happens because the fil is played before it's ready, since ComponentWillReceiveProps calls play. I made a pull request that fixes this. #37

**Comment by mspae** [comment]
:+1:
