### ISSUE TITLE
ReferenceError: window is not defined.

### ISSUE THREAD

**Issue by kevinchau321** [mspae/react-wavesurfer#38]
Hello, I'm trying to use react-wavesurfer with one of my react components. I'm using webpack, so when I try the import statement:
```
import Wavesurfer from 'react-wavesurfer';
```

I get a server-side error:
```
ReferenceError: window is not defined
```

**Comment by kevinchau321** [comment]
This may or may not be an issue with Wavesurfer itself and Babel/Webpack:
https://github.com/katspaugh/wavesurfer.js/issues/767

**Comment by mspae** [comment]
Duplicate of https://github.com/mspae/react-wavesurfer/issues/21
