### ISSUE TITLE
Accessing PropTypes via the main React package is deprecated

### ISSUE THREAD

**Issue by rijk** [mspae/react-wavesurfer#39]
`Warning: Accessing PropTypes via the main React package is deprecated. Use the prop-types package from npm instead.`

From https://facebook.github.io/react/docs/typechecking-with-proptypes.html: 

> Note: React.PropTypes is deprecated as of React v15.5. Please use the prop-types library instead.

Should be a pretty easy fix:

`import PropTypes from 'prop-types';`

**Comment by mspae** [comment]
Can you open a PR? Thanks!
