### ISSUE TITLE
I am not able to run the code

### ISSUE THREAD

**Issue by kaviproject** [mspae/react-wavesurfer#42]
I just downloaded the code and I am trying to run using npm start run. Its throwing below error. Can anyone help me for the execution.

ERROR in multi main
Module not found: Error: Cannot resolve module 'run' in C:\Users\kparupati\Downloads\react-wavesurfer-master
 @ multi main

ERROR in ./src/plugins/regions.js
Module not found: Error: Cannot resolve 'file' or 'directory' ../../src/plugin/wavesurfer.regions.js in C:\Users\kparupati\Downloads\react-wavesurfer-master\src\plugins
 @ ./src/plugins/regions.js 19:0-49

ERROR in ./src/plugins/minimap.js
Module not found: Error: Cannot resolve 'file' or 'directory' ../../src/plugin/wavesurfer.minimap.js in C:\Users\kparupati\Downloads\react-wavesurfer-master\src\plugins
 @ ./src/plugins/minimap.js 19:0-49

ERROR in ./src/plugins/timeline.js
Module not found: Error: Cannot resolve module 'wavesurfer.js/dist/plugin/wavesurfer.timeline.js' in C:\Users\kparupati\Downloads\react-wavesurfer-master\src\plugins
 @ ./src/plugins/timeline.js 27:0-96
webpack: Failed to compile.

**Comment by tf** [comment]
I'm having similar problems. Running `npm start` fails with errors like
```
ERROR in ./src/plugins/timeline.js
Module not found: Error: Cannot resolve module 'wavesurfer.js/dist/plugin/wavesurfer.timeline.js' in /home/user/code/react-wavesurfer/src/plugins                                                                         
 @ ./src/plugins/timeline.js 27:0-96
```
`npm run build` also fails for similar reasons. `npm run build:main` and `npm run build:main.min` work fine, though, which is enough for me at the moment.

**Comment by kaviproject** [comment]
I am just planning to use region.js but it's throwing errors. I tried with npm run build:main and npm run build: main.min working fine.. But I am not able to run the existing example. anyone suggest me the correct approach?

**Comment by briankeane** [comment]
As a temporary solution I copied all the un-minimized files in node_modules/wavesurfer.js/plugin/ to node_modules/wavesurfer.js/dist/plugin (after running npm install).  Not a great solution but might keep you going until someone posts something better.

I also had a port collision going, so I had to add a --port 1234 option to the start script, then point my browser to http://localhost:1234/

Hope this helps

**Comment by mspae** [comment]
Is fixed, apparently wavesurfer.js does not include the non-minified plugin files anymore. Please update to v0.8.4

**Comment by briankeane** [comment]
@mspae you rock
