### ISSUE TITLE
Suggestion: Use react-measure instead of custom window resize handler

### ISSUE THREAD

**Issue by tf** [mspae/react-wavesurfer#49]
I understand that adding another dependency to the package might not be a popular move. Still I wanted to post a link to [a branch that I'm using](https://github.com/mspae/react-wavesurfer/compare/master...tf:measure) which replaces a bunch of code in this project with a rather straightforward usage of [`react-measure`](https://github.com/souporserious/react-measure/tree/1.4.7).  

Since `react-measure` relies on resize and mutation observers, responsive resizing also works if one of the parent elements changes its size while window remains unchanged. This was a requirement in my case.
 
The branch is an extension of the changes proposed in #48.

**Comment by mspae** [comment]
Actually I have been working on wavesurfer.js version 2 which supports resizing (if the waveform is setup to be the width of the container – e.g. there is no scrollbar (See https://github.com/katspaugh/wavesurfer.js/blob/master/src/wavesurfer.js#L340)) – Unfortunately I don't have any free time to push that project forward. Ideally v2 (which also includes lots of other features) should be finalised (although it is already pretty bug free as far as I know.) – See status of that here: https://github.com/katspaugh/wavesurfer.js/issues/1092 – Ideally react-wavesurfer should be updated to include support for wavesurfer 2 (The refactor of wavesurfer was mainly motivated by the requirements of react-wavesurfer: the new version is architected to work better with module bundlers, this will allow this lib to be "batteries included" – so no dependencies to wavesurfer) – So if you or anyone sees fit to work on this I would extremely happy to coordinate and/or make them maintainer of this repo.

**Comment by tf** [comment]
Sorry for taking forever to respond here. But as you said free time is a limited resource. :wink: 

I agree that with Wavesurfer providing a responsiveness feature itself, this question becomes out of scope for react-wavesurfer.

Since my changes to Wavesurfer will go into v2, I'll be living on a fork anyway for now until that is released and react-wavesurfer is updated.

Once I start working in this area again, I'll be happy to help making v2 compatibility happen.
