### ISSUE TITLE
Uncaught TypeError: Failed to set the 'value' property on 'AudioParam': The provided float value is non-finite

### ISSUE THREAD

**Issue by Bran1304** [mspae/react-wavesurfer#62]
Keep getting this error after updating to 0.8.5, the error points to the setVolume function in wavesurfer.min.js. 

Can I get any help with this please?
Thanks

**Comment by mspae** [comment]
Can you post the code?

**Comment by mspae** [comment]
Okay I see it in the examples. I'm on it.

**Comment by mspae** [comment]
@Bran1304  Okay there were two issues here:

* There was a check if `this.props.value != null` – this obviously failed if it was simply undefined.
* I've moved the wavesurfer plugin files outside of this library. Maintaining the very complicated and brittle configuration for shimming all the plugins together. (Essentially shoe-horning a global-variable-style architecture into a module-bundler architecture) – Please read the README how you need to adapt your code.

Please update to v0.8.6

And sorry this even cropped up, I should have tested the build more thoroughly.
