### ISSUE TITLE
Webpack plugin use examples

### ISSUE THREAD

**Issue by jonathancalb** [mspae/react-wavesurfer#64]
I have a project in webpack and I can't get regions plugin working. I get this error: "wavesurfer.addRegion is not a function"
Probably I'm getting something wrong but I can't find any examples of plugin use in a webpack project.
It will be nice to have some examples as I guide so it's easier to use.

**Comment by mspae** [comment]
Sorry for asking the obvious: Did you look at this section: https://github.com/mspae/react-wavesurfer#prerequisites-and-common-pitfalls

The way the bundling works changed in the last release.

**Comment by avroshk** [comment]
I am facing similar problems as @jonathancalb while trying to use Plugin components (in my case Timeline). 

I tried the instructions in pre-requisites and common pitfalls. 
1. I load wavesurfer.js into WaveSurfer like so (works good)
`import WaveSurfer from 'wavesurfer';`
2. I load the component like so 
`import WavesurferComponent from 'react-wavesurfer';`
3. I am also able to successfully load Timeline component like so 
`import TimelinePluginComponent from 'react-wavesurfer/plugins/timeline';`
4. But loading/requiring wavesurfer.timeline.min.js throws an error saying 'wavesurfer' could not be found
`import TimelinePluginObject from 'wavesurfer.js/dist/plugin/wavesurfer.timeline.min.js';`
> Module not found: Can't resolve 'wavesurfer' in '/........../node_modules/wavesurfer.js/dist/plugin'

So, I cannot set window.WaveSurfer.Timeline and am not able to use the Timeline component.

I am using webpack. I am not sure if there is still something missing with my webpack config or something else. I am using _wavesurfer.js 1.4.0_.

Please let me know if you have any insights into what might be wrong here. Thank you!

**Comment by mspae** [comment]
@avroshk @jonathancalb Do you have this section in your webpack config:

```javascript
  // provide WaveSurfer as a globally accessible variable
  plugins: [
    new webpack.ProvidePlugin({
      WaveSurfer: 'wavesurfer.js'
    })
  ],
  // Alias `wavesurfer` to the correct wavesurfer package.
  // (wavesurfer.js has some non-standard naming convention)
  resolve: {
    alias: {
      wavesurfer: require.resolve('wavesurfer.js')
    }
  },
```

**Comment by avroshk** [comment]
@mspae Yeah, I have included those in my webpack config. I cloned your repo and ran your examples and they run okay. My webpack config is sort of a mess (aftermath of ejecting from 'yarn'). So, I think I need to look closely if there is something in the webpack config that might be preventing the plugins to load. I used the create-react-app tool. Maybe, I'll also try this without it.

I'll update here if I find anything. Thanks.

**Comment by avroshk** [comment]
I was able to get timeline plugin running on my react app. I quit using "[create-react-app](https://github.com/facebookincubator/create-react-app)" tool and just started from the scratch with Babel, Webpack and yarn. From where I left off, it seems the webpack config settings that @mspae suggested were overwritten by the webpack config settings of create-react-app tool or maybe simply I wasn't able to configure the dependency for wavesurfer.js plugins.

**Comment by mspae** [comment]
Awesome. I'll close this then.

**Comment by avroshk** [comment]
Thank you. I realized the root of the problem was the use of wavesurfer as a global variable which is not the react-way of doing things. I'm pretty sure these things will resolve once we move to wavesurfer.js@2.0.0
