### ISSUE TITLE
Wave stops advancing/sending callbacks when running on Safari (mac) 

### ISSUE THREAD

**Issue by pinhassi** [mspae/react-wavesurfer#67]
Use case:
1. Open file and play when ready - sounds plays, wave advancing, onPosChange is called (OK).
2. Pause player - Sound stops,  wave not advancing, onPosChange callback is not called (OK).
3. Play again - Sound plays, wave **not advancing**, **onPosChange callback is not called** (BUG).
4. Click on wave to seek - sound switches to new position, onSeek is called, wave switch position **but doesn't advance** according to playback (BUG).

**Comment by mspae** [comment]
I think this is a bug with wavesurfer. Closing this issue. Please comment/reopen if you feel different.
